version: '3'
services:
  primary:
    hostname: primary
    container_name: primary
    image: primary
    build:
      dockerfile: postgresql-archiving.dockerfile
      context: .
    volumes:
      - vol-primary:/var/lib/postgresql/data
      - vol-archive:/archive
volumes:
  vol-primary:
  vol-archive:
