version: '3'
services:

  primary:
    hostname: primary
    container_name: primary
    image: primary
    build:
      dockerfile: postgres.dockerfile
      context: .
    volumes:
      - vol-primary:/var/lib/postgresql/data

  sysadm:
    hostname: sysadm
    container_name: sysadm
    image: sysadm
    build:
      dockerfile: sysadm.dockerfile
      context: .
    stdin_open: true
    tty: true
    volumes:
      - vol-primary:/primary

volumes:
  vol-primary:
