version: '3'
services:
  db-primary:
    hostname: primary
    container_name: primary
    image: "my_postgres"
    volumes:
      - vol-primary:/var/lib/postgresql/data
      - vol-archive:/archive
  db-standby:
    hostname: standby
    container_name: standby
    image: "my_postgres"
    volumes:
      - vol-standby:/var/lib/postgresql/data
      - vol-archive:/archive
  postclient:
    hostname: client
    container_name: client
    image: "postclient"
    stdin_open: true
    tty: true

volumes:
  vol-primary:
  vol-standby:
  vol-archive: